version: "3.9"
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    image: todo
    depends_on:
      - mysqldb
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

volumes:
  db: